
name: Publish package to GitHub Packages
on: push
jobs:
  publish:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./change-manager
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
        # with:
        #   repository: 
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1
      - name: Graddle wrapper
        run: gradle wrapper --gradle-version 7.5.1 
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: copy properties file
        run: cp ./gradle.properties ~/.gradle/
      - name: Debug
        run: |
              pwd
              ls -larth
              ls -A ~/ 
      - name: Publish package
        # working-directory: ./change-manager
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
          gradle-executable: ./change-manager/gradle/wrapper
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}